# Configuración Principal
owner: ferreteriaelgreco
repo: statuspage

# Sitios e servizos a Monitorear
sites:
  - name: "ERP Odoo Corporativo (Facturación, Web principal...)"
    url: https://ferreteriaelgreco.odoo.com
    method: GET

  - name: "Microsoft 365 (Contas corporativas @ferreteriaelgreco.es)"
    url: https://microsoftonline.com
    method: GET

  - name: "Zoho Mail (Correo corporativo @practicas.ferreteriaelgreco.es)"
    url: https://zoho.com
    method: GET

# Configuración páxina Estado Pública
status-page:
  name: "Páxina de estado de servizos - Ferretería El Greco"
  introMessage: "Panel de estado das infraestruturas tecnolóxicas de Ferretería el Greco. Páxina en construcción. Para calquera dúbida contacta na ligazón superior"
  cname: status.ferreteriaelgreco.es
  baseUrl: /
  navbar:
    - title: "Apertura de incidencia - Contacto"
      url: https://www.ferreteriaelgreco.es/contactus/soporteplataformas

assignees:
  - ferreteriaelgreco
